version: '3'

services:
  # database:
  #   container_name: keso_db
  #   image: postgres:14.2
  #   healthcheck:
  #     test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgresql_user']
  #     timeout: 45s
  #     interval: 10s
  #     retries: 10
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgresql_user
  #     - POSTGRES_PASSWORD=docker
  #     - POSTGRES_DB=keso_db
  #   volumes:
  #     - db-data:/var/lib/postgresql/data/
  #   ports:
  #     - '127.0.0.1:5432:5432'
  #   networks:
  #     - keso_network

  portfolio:
    container_name: portfolio
    build:
      context: .
      dockerfile: ./core/portfolio/Dockerfile
      target: dev
    env_file:
      - ./core/portfolio/.env
    ports:
      - '127.0.0.1:3000:3000'
    volumes: ['./core/portfolio:/app/core/portfolio']
    command: ['yarn', 'start']
    restart: always
    networks:
      - keso_network

networks:
  keso_network:

volumes:
  db-data:
